swagger: '2.0'
info:
    title: Generated Game-API
    version: 1.0.0
paths:
    /games:
        get:
            responses:
                '200':
                    description: Successful response - returns an array of `Game` entities.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Game'
            operationId: getGames
            summary: List All Games
            description: Gets a list of all `Game` entities.
        post:
            parameters:
                -
                    name: body
                    description: A new `Game` to be created.
                    schema:
                        $ref: '#/definitions/Game'
                    in: body
                    required: true
            responses:
                '201':
                    description: Successful response.
            operationId: createGame
            summary: Create a Game
            description: Creates a new instance of a `Game`.
    '/games/{id}':
        get:
            responses:
                '200':
                    description: Successful response - returns a single `Game`.
                    schema:
                        $ref: '#/definitions/Game'
            operationId: getGame
            summary: Get a Game
            description: Gets the details of a single instance of a `Game`.
        put:
            parameters:
                -
                    name: body
                    description: Updated `Game` information.
                    schema:
                        $ref: '#/definitions/Game'
                    in: body
                    required: true
            responses:
                '202':
                    description: Successful response.
            operationId: updateGame
            summary: Update a Game
            description: Updates an existing `Game`.
        delete:
            responses:
                '204':
                    description: Successful response.
            operationId: deleteGame
            summary: Delete a Game
            description: Deletes an existing `Game`.
        parameters:
            -
                name: id
                description: A unique identifier for a `Game`.
                in: path
                required: true
                type: string
definitions:
    Game:
        title: Root Type for Game
        description: ''
        type: object
        properties:
            _id:
                type: string
            name:
                type: string
            price:
                format: double
                type: number
        example:
            _id: 632da5aff385b47812144c57
            name: Estrella Reilly
            price: 59.69
