openapi: 3.0.2
info:
    title: Games-API
    version: 1.0.0
    description: '### This is a Swagger UI for our Games API'
paths:
    /games:
        summary: Get a list of all games
        description: Returns a list of all games in API
        get:
            tags:
                - games
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of games:
                                    value:
                                        - Witcher 3
                                        - Cyberpunk 2077
                    description: Returns a list of games
            summary: Get a list of all games
            description: Returns a list of all games in API
    '/games/{id}':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Single game full details:
                                    value:
                                        id: 3
                                        name: Minecraft
                                        price: 29.99
                    description: Full details of a game with the given id
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: |
                        Invalid request data
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Game not found
            deprecated: false
            operationId: id
            summary: Get full details of a game
            description: Returns full details of a game with the given id
components:
    schemas:
        Error:
            title: Root Type for Error
            description: Error message
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
